name: Sync with localization-zh_Hans

on:
  schedule:
    - cron: '0 16 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout out
        uses: actions/checkout@v4
        with:
          repository: hanamizuki-ai/stable-diffusion-webui-localization-zh_Hans
          ref: master
          path: .
      - name: Set up Git
        run: |
          git config --local user.email "github-action@users.noreply.github.com"
          git config --local user.name "GitHub Action"
      - name: Sync with localization-zh_Hans
        run: |
          git remote add github https://github-action:$GITHUB_TOKEN@github.com/aoxiang1221/sd-aoxiang.git
          git push -f github master:localization-zh_Hans
