name: Sync with controlnet

on:
  schedule:
    - cron: '0 16 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main
      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
      - name: Sync with controlnet
        run: |
          git remote add upstream https://github.com/Mikubill/sd-webui-controlnet.git
          git fetch upstream
          git checkout main
          git reset --hard upstream/main
          git push origin main:controlnet --force
